# **학업 일지**

#### 오늘의 한마디  

> **선형대수의 이해를 바탕으로 numpy의 선형대수 연산을 이해하고 연습하자**

## 1. 강의 정리

#### *Numpy 연습을 통한 벡터와 행렬의 기본개념 숙지*

### 1.1 Numpy와 선형대수와의 연관성 공부

#### 1.1.1 Numpy 객체의 특징  
- 효율적인 데이터 처리를 위하여 C언어를 통한 데이터 관리를 채택했다.  
Array가 만들어지는 순간 메모리를 데이터 타입에 맞추어 객체를 생성하므로 데이터 타입에 대한 명시는 필수적이다.

In [72]:
import numpy as np
np_array = np.array([1,2,3,4,5], dtype=float)

- c와 numpy는 아래 그림과 같이 데이터타입이 compatible하기 때문에 실제로 통합가능하다.

<img src="./img/c_numpy_datatype.png" alt="c_numpy_datatype" style="width: 900px;"/>

#### 1.1.2 Numpy의 다양한 함수 및 유의사항

- 기본 데이터와  
`transpose 된 열벡터를 반환하지 않는다.`

In [73]:
import numpy as np
a = [1,2,3,4]
test_array = np.array(a,float)
transpose = test_array.T
print(transpose, test_array)

[1. 2. 3. 4.] [1. 2. 3. 4.]


In [74]:
print(test_array.ndim) # demension of array
print(test_array.size) # number of data
print(test_array.nbytes) # total bytes of array : float64 * <4 data>

1
4
32


In [75]:
# check order of flatten function
test_matrix = np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]], dtype=np.float64)
flatten_matrix = test_matrix.flatten()
print(test_matrix)
print(flatten_matrix)

[[[ 1.  2.  3.  4.]
  [ 5.  6.  7.  8.]]

 [[ 9. 10. 11. 12.]
  [13. 14. 15. 16.]]]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16.]


- Initializing function

In [76]:
print(np.arange(1,10,0.5, dtype=np.float64))
print(np.zeros((2,5),float))
print(np.empty((2,5),float))
print(np.ones((2,5),float))

[1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5 9.  9.5]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


- Rank of vector and axis, 

In [77]:
a = np.array([[1,2,3]])
b = np.array([[2,3,4]])
np.concatenate((a,b), axis=0)

array([[1, 2, 3],
       [2, 3, 4]])

In [78]:
# add axis
b = np.array([5,6])
b[np.newaxis, :]

array([[5, 6]])

- broadcasting

In [79]:
a = np.array([[1,2,3,4]])
b = np.array([[0],[1],[2]])
a + b

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6]])

In [80]:
a = np.arange(10)
a>5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [81]:
np.any(a>5) # all : boolen array에서 any, all attribute로도 사용가능

True

In [82]:
test_a = np.array([1,2,3])
test_b = np.array([2,1,3])
test_a > test_b

array([False,  True, False])

In [83]:
np.logical_and(test_a > 1, test_b < 2) # or, not

array([False,  True, False])

In [84]:
a = np.array([1, np.NaN, np.Inf], float)
np.isnan(a), np.isinf(a)

(array([False,  True, False]), array([False, False,  True]))

In [85]:
a = np.array([1,2,3,4])
np.where(a>2), np.where(a>2)[0] # tuple 형태 조심

((array([2, 3], dtype=int64),), array([2, 3], dtype=int64))

In [66]:
np.where(a>2, 3, 4)

array([4, 4, 3, 3])

- Fancy index

In [87]:
a = np.array([2,4,6,8], float)
b = np.array([0,1,0,2], int)
a[b], a.take(b)

(array([2., 4., 2., 6.]), array([2., 4., 2., 6.]))

In [88]:
a = np.array([[1,4],[9,16]], float)
b = np.array([0,0,1,1,0], int)
c = np.array([0,1,1,1,1], int)
a[b,c]

array([ 1.,  4., 16., 16.,  4.])

#### 1.1.3 행렬과 연관있는 함수

In [39]:
np.identity(n=3,dtype=float) # identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [40]:
np.eye(3,5,k=2) # diagonal feature : k is start point of 1.

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [41]:
array1 = np.arange(9).reshape((3,3))
print(array1)
print(np.diag(array1)) # array of diagonal data
print(np.diag(array1,k=1))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 4 8]
[1 5]


- Element_wise operations
+, -, * (Hadamard product), / 

- Dot product  
<array> @ <array>
<array>.dot(<other array>)
    
- Transpose
<array>.T

- L1, L2 - norm

In [105]:
a = np.array([1,5,3])
b = np.array([2,3,7])
print('L1-norm distance = ', np.sum(np.abs(a-b)))
print('L2-norm distance = ', np.sqrt(np.sum((a-b)*(a-b))))

L1-norm distance =  7
L2-norm distance =  4.58257569495584


- Inverse matrix, pseudo-inverse matrix(Moore-Penrose matrix)

In [107]:
X = np.array([[1,-2,3],[7,5,0],[-2,-1,2]])
np.linalg.inv(X)

array([[ 0.21276596,  0.0212766 , -0.31914894],
       [-0.29787234,  0.17021277,  0.44680851],
       [ 0.06382979,  0.10638298,  0.40425532]])

In [108]:
X = np.array([[0,1],[1,-1],[-2,1]]) # n <= m인 경우 무수히 많은 해중 하나를 고를 수 있다.
np.linalg.pinv(X)

array([[ 5.00000000e-01,  1.11022302e-16, -5.00000000e-01],
       [ 8.33333333e-01, -3.33333333e-01, -1.66666667e-01]])

In [110]:
X2 = np.array([[0,3,1],[2,1,-2]]) # n >= m인 경우 선형 회귀분석에 사용할 수 있다.
np.linalg.pinv(X2)

array([[-0.02247191,  0.2247191 ],
       [ 0.29213483,  0.07865169],
       [ 0.12359551, -0.23595506]])

#### 1.1.4 통계와 연관있는 함수

In [38]:
np.random.uniform(0,1,10).reshape(2,5) # uniform distribution

array([[0.38136018, 0.49430517, 0.75004363, 0.55968578, 0.30935858],
       [0.62028107, 0.43043212, 0.07042576, 0.65312194, 0.1463746 ]])

In [42]:
np.random.normal(0,1,10).reshape(2,5) # normal distribution

array([[-0.60700352, -1.61824076, -0.63078288, -2.50820422,  0.56561227],
       [ 0.29673482, -0.99866315, -1.10885601, -0.35309313,  2.50787495]])

In [43]:
test_array = np.arange(1,11)
np.sum(test_array)

55

In [44]:
np.mean(test_array)

5.5

In [45]:
np.std(test_array)

2.8722813232690143

In [46]:
np.var(test_array)

8.25

- 수학 연산자  
exponential : exp, log, log10, log2, power, sqrt  
trigonometric : sin, cos, tan, acsin, arccos, atctan
hyperbolic : sinh, cosh, tanh, acsinh, arccosh, atctanh

#### 1.1.5 axis가 적용되는 함수

일반적으로 구역을 결정하는 경우에 사용된다.
- <array>.sum(axis=0) 외에 예시 sum, std, mean, var
- np.argmax(a, axis=0) : argmin, argsort, 

## 2. 피어 세션 정리

#### 2.1 스터디

- 2.1.1 파이썬의 실행 에러와 곧 마주할 에러에 대한 설명을 했다. (발표: 배새봄)  
 - 다양한 에러를 숙지하고 있어야 하며 특히 파일 관리 파트에 들어가면서 겪게 될 OS에러에 대한 설명이 추가되었다.`

- 2.1.2 웹 크롤링 (발표: 안동주)  
 - 웹크롤링에 대한 request모듈과 html을 해석하여 크롤링한 실제 프로그램을 짜왔으며 그에 대한 리뷰를 발표했다. 
 - 실제 프로그램이 데이터를 가져오는 것을 보는 것만으로도 큰 도움이 되었다.

#### 2.2 원하는 진로를 잡고 논문 공부

- Deep Learning : Yann LeCnn, Yoshua Bengio & Geoffrey Hinton
딥러닝에 대한 전반적인 이해를 돕고 AI 논문에 대한 언어 장벽을 없애기 위해 필요하며 발표 예정

## 3. 진행중인 공부 및 신규 공부 목록

- 진행중인 공부  

    - Jupyter Notebook 심화 공부  
    - Vim 에디터 심화 커스터마이징  
    - Deep learning 논문 읽고 정리하기
    - AI 기본 수학 : Mathematics for Machine learning - Marc Peter Deisenroth
    - 파이썬 파일관리를 기본으로 해서 프로젝트 하나 진행해보기
    - 웹 클로링 및 데이터 처리 연습 익숙해지기

- 신규 공부 목록  
 
    - MYsql에 대한 개발환경 설정과 기본 명령어 배우기

- 완료한 공부  

## 4. 감사한 일

- 수학에 대한 문제는 물어보는 것만으로도 큰 도움이 되는데 잘 답변까지 해주신 문영기 조교님에게 감사합니다.
- 웹 크롤링을 통하여 데이터를 다루는 기본기에 대해서 구체적으로 보여준 안동주님에게 감사합니다.
- 더 밝은 마음가짐으로 피어세션에 참여하는 우리 팀 모두에게 감사합니다.