# Numpy

In [1]:
import numpy as np
import torch

In [2]:
ndarray = np.random.uniform(0,1,(3,4))
nd2 = np.ndarray(shape=(3,4),dtype=float) # attribute : nbyte, 
nd3 = np.arange(24).reshape(2,3,4)

In [3]:
torch.arange(24).view(2,-1)

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

- algbra 기본연산 :   
dot product, broadcast,  
ndarray가 가진 정보 : dtype, shape, values, size(data개수), nbytes  
reshape - 데이터를 가진 matrix를 모양변환, 특별한 의미 없이 모양바꾸는 함수 (-1,4)

- 초기화 : np.arange(10), np.zeros(shape= , dtype) # np.ones, np.empty  

In [24]:
np.ones_like(ndarray) # zeros, empty  
np.identity(3).transpose()  # .T
np.eye(5,3,2) # row, column, start-point / 어디에 쓰일까??

array([[0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [8]:
np.diag(ndarray) # 대각선만 추출

array([0.62743801, 0.07491698, 0.49257112])

- 분포  

In [ ]:
np.random.uniform(0,1,(3,4)) # Population parameter, shape / normal, exponential, 

- 통계학 연산 : sum, mean, std, median, var  + 추가항 : axis <br>
연산, 함수 쓸거있으면 다있으니 검색해라 : 
exp - softmax,  

- 붙이기 : + 추가 axis  

In [12]:
np.vstack((ndarray,ndarray))  
np.hstack((ndarray,ndarray))  
np.concatenate((ndarray,ndarray),axis=0)

array([[0.62743801, 0.30325037, 0.63317008, 0.48787668],
       [0.76770605, 0.07491698, 0.93301027, 0.19632992],
       [0.89882369, 0.98097705, 0.49257112, 0.14373277],
       [0.62743801, 0.30325037, 0.63317008, 0.48787668],
       [0.76770605, 0.07491698, 0.93301027, 0.19632992],
       [0.89882369, 0.98097705, 0.49257112, 0.14373277]])

- 축 추가 :

In [14]:
ndarray[np.newaxis,:]

array([[[0.62743801, 0.30325037, 0.63317008, 0.48787668],
        [0.76770605, 0.07491698, 0.93301027, 0.19632992],
        [0.89882369, 0.98097705, 0.49257112, 0.14373277]]])

- 비교 연산 : broadcasting과 비슷한 개념  
np.any, np.all, np.logical_and, # or, not

- np.where 두가지방법  
np.where(a > 0,3,2) # 1번째 방법 참이면 3, 거짓이면 2 출력 - 기준을 잡아 원하는 수로 출력가능  
np.where(`조건`) # index값 반환

- np.argmin() # argmax, argsort - index 반환 / min, max, sort

- boolean index : bool array를 참조하여 True의 index값만 뽑는다.
- fancy index : index array를 참조하여 값을 뽑는다. # 여러 index array사용가능 = .take


- 저장 : np.savetxt(`name`,`array`,delimiter=',') # np.loadtxt() - scv로  
np.save(`name`,`array`) # pickle로  
불러오기 : np.load(`name`) # scv로부터

# 선형대 함수

In [17]:
np.linalg.pinv
np.linalg.inv
np.linalg.norm([4,4]) # l2-norm

5.656854249492381

# Pytorch

In [29]:
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np

In [30]:
np_array = np.random.uniform(0,1,(2,4,5))
x_torch = torch.from_numpy(np_array)

torch.rand((2,3)) # ones, zeros,

tensor([[0.4925, 0.7259, 0.3973],
        [0.6613, 0.6350, 0.2677]])

In [12]:
a = torch.tensor([2., 3.], requires_grad=True)
b = torch.tensor([6., 4.], requires_grad=True)
Q = 3*a**3 - b**2

In [13]:
Q.backward(gradient=torch.tensor([2.,2.]))

In [14]:
a.grad

tensor([ 72., 162.])

In [32]:
torch.ones_like(x_torch) # rand_list, 

tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]], dtype=torch.float64)

- torch가 가지고 있는 정보 shape, dtype, device, size(shape가진 객체), 

In [ ]:
- torch 연산

torch.cat([x_data,x_data]) # dim 

torch.stack([x_data,x_data]) # dim

x_data.mul(x_data) # x_data * x_data
x_data.matmul(x_data) #  x_data @ x_data

x_data.unsqueeze(dim=0) # squeeze

- 여러가지 함수

import torch.nn.functional as F
tensor = torch.FloatTensor([0.5, 0.7, 0.1])
a_tensor = F.softmax(tensor, dim=0)
a_tensor

In [ ]:
argmax(), one_hot()

- 모델 구조

In [36]:
import torchvision

model = torchvision.models.resnet18(pretrained=True)
data = torch.rand(1, 3, 64, 64)
labels = torch.rand(1, 1000)

prediction = model(data) # forward pass
loss = (prediction - labels).sum()
loss.backward()
optim = torch.optim.SGD(model.parameters(),lr=1e-2, momentum=0.9)
optim.step

<bound method SGD.step of SGD (
Parameter Group 0
    dampening: 0
    lr: 0.01
    momentum: 0.9
    nesterov: False
    weight_decay: 0
)>

In [ ]:
- 미분 구조

In [37]:
a = torch.tensor([2., 3.], requires_grad=True)
b = torch.tensor([6., 4.], requires_grad=True)

Q = 3*a**3 + b**2 # 목적함수

external_grad = torch.tensor([1., 1.]) 
Q.backward(gradient=external_grad) # 반복해서 실행시키면 오류
print(a.grad) # 미분값을 a 객체에 저장하네
print(b.grad)

x = torch.rand(5,5) # frozen parameters 미분값 계산 안해
y = torch.rand(5,5)
z = torch.rand((5,5), requires_grad=True)

model = torchvision.models.resnet18(pretrained=True)

for param in model.parameters(): # 모델의 파라메터마다 requires_grad 존재
    param.shape
    param.requires_grad

tensor([36., 81.])
tensor([12.,  8.])
